#LAN Linker Configuration
#Thu Mar 05 23:24:56 CST 2026
device.name=LAPTOP-DCV9EMBC
local.history=
local.root_path=C\:\\Users\\vc619
network.discovery=true
network.interface=Auto
quick.expire_hours=1
quick.max_file_mb=1024
quick.max_text_len=32767
quick.path=E\:\\IdeaProjects\\LAN-Linker\\quick_share
security.global_auth=false
security.pin=123456
security.session_expiry=1
server.allow_upload=true
server.port=8080
system.auto_start=false
system.debug=false
system.minimize_tray=true
ui.dark_mode=false
ui.scale=120
